
export const Brands = [
    "KALINI",
    "Ramraj",
    "VASTRAMAY",
    "9rasa",
    "Anug by SOJANYA",
    "Sangria",
    "TULIP 21",
    "DIVINATION",
    "Clora Creation",
    "Taavi",
    "PRAKASAM COTTON",
    "Sethukrishna",
    "INVICTUS",
    "Peter England Elite",
    "Arrow",
    "Mr Bowerbird",
    "MANQ",
    "Jack & Jones",
    "Louis Philippe",
    "Marks & Spencer",
    "Van Heusen",
    "WROGN",
    "Louis Philippe Sport",
    "Allen Solly",
    "H&M",
    "Van Heusen Sport",
    "Roadster",
    "Kotty",
    "Dennis Lingo",
    "HRX by Hrithik Roshan",
    "HIGHLANDER",
    "Levis",
    "IVOC",
    "Bene Kleed",
    "Pepe Jeans",
    "HERE&NOW",
    "ADIDAS",
    "Powerlook",
    "Jockey",
    "Mast & Harbour",
    "Snitch",
    "The Souled Store",
    "URBAN SCOTTISH",
    "U.S. Polo Assn.",
    "Peter England",
    "DAMENSCH",
    "XYXX",
    "AMUL COMFY",
    "Thomas Scott",
    "Campus Sutra",
    "Moda Rapido",
    "THE BEAR HOUSE",
    "Puma",
    "Red Tape",
    "Flying Machine",
    "Blackberrys",
    "FCUK",
    "Louis Philippe Ath.Work",
    "House of Pataudi",
    "Anouk",
    "KISAH",
    "Jompers",
    "See Designs",
    "Molly & Michel",
    "Nike",
    "Skechers",
    "ASICS",
    "Raymond",
    "Liberty",
    "Provogue",
    "Mochi",
    "Bata",
    "CODE by Lifestyle",
    "Cantabil",
    "Park Avenue",
    "SLOWLORIS",
    "The Indian Garage Co",
    "BLUE TYGA",
    "Nautica",
    "Justanned",
    "max",
    "High Star",
    "Reebok",
    "PERFKT-U",
    "DENNISON",
    "Hypernation",
    "Duke",
    "Sztori",
    "bigbanana",
    "Kalenji By Decathlon",
    "sven suits",
    "KLOTTHE",
    "hangup trend",
    "TAHVO",
    "MANGO MAN",
    "Peter England Casuals",
    "Trendyol",
    "98 Degree North",
    "GRIMELANGE",
    "United Colors of Benetton",
    "Lux Cottswool",
    "HAP",
    "NEVA",
    "Aerowarm",
    "VIMAL JONNEY",
    "Stormborn",
    "BULLMER",
    "Technosport",
    "Cultsport",
    "plusS",
    "UnderJeans by Spykar",
    "Maniac",
    "Kook N Keech",
    "Dpassion",
    "Reslag",
    "Harvard",
    "ether",
    "Indian Terrain",
    "SHRESTHA BY VASTRAMAY",
    "VASTRAMAY PLUS",
    "KRAFT INDIA",
    "SOJANYA",
    "Vastraa Fusion",
    "CAMISON",
    "Dollar",
    "Alexvyan",
    "Plutus",
    "FabSeasons",
    "haus & kinder",
    "THE CLOWNFISH",
    "Zacharias",
    "Hangup",
    "Vgyaan"
  ]